# Generated by Django 4.2.6 on 2023-10-16 12:00

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UploadedFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file1", models.FileField(upload_to="uploads/")),
                ("file2", models.FileField(upload_to="uploads/")),
            ],
        ),
    ]
