from django.urls import path
from . import views
urlpatterns = [
    path('upload/', views.merge_and_display, name='upload_and_display'),
    path('upload_mapping/', views.upload_mapping, name='upload_mapping'),
    path('update_and_download/', views.update_and_download, name='update_and_download'),
    path('Naming_Convention/', views.Naming_Convention, name='Naming_Convention'),
    path('mapping_upload/', views.MappingData, name='mapping_upload'),
    path('get_unique_values/', views.get_unique_values, name='get_unique_values'),
    path('get_unique_values1/', views.get_unique_values1, name='get_unique_values1'),
    path('process_data/', views.process_data, name='process_data'),
    path('save_negative_exposures/', views.save_negative_exposures, name='save_negative_exposures'),
    path('handle_selected_values/', views.handle_selected_values, name='handle_selected_values'),
    path('download_csv/', views.download_csv, name='download_csv'),
    path('download_csv1/', views.download_csv1, name='download_csv1'),
    # path('claims/', views.claims, name='claims'),
    # Changed this line to have a unique path
    path('os-upload/', views.os_file_upload, name='os_file_upload'),
    path('claims-upload/', views.claims_file_upload, name='claims_file_upload'),
    path('process-claims-data/', views.process_claims_data, name='process_claims_data'),
    path('process-os-data/', views.process_os_data, name='process_os_data'),
    path('display-results/', views.display_results, name='display_results'),
    path('display-claims-results/', views.display_claims_results, name='display_claims_results'),
    path('display-os-results/', views.display_os_results, name='display_os_results'),
    path('fetch-unique-dates/', views.fetch_unique_dates, name='fetch_unique_dates'),
    path('download_processed_data/', views.download_processed_data, name='download_data'),
    path('download_processed_data_UAE/', views.download_processed_data_UAE, name='download_data_UAE'),
    path('download_new_df/', views.download_new_df_csv, name='download_new_df_csv'),
    path('download_processed_data_os_UAE/', views.download_processed_data_os_UAE, name='download_data_Os_UAE'),
    path('download_reported_claims/', views.download_reported_claims, name='download_reported_claims'),
    path('download_reported_claims_UAE/', views.download_reported_claims_UAE, name='download_reported_claims_UAE'),
    path('process_data/PremiumChecks/', views.premium_checks, name='process_data_premium_checks'),
    path('checks-left/', views.checks_left_view, name='checks_left'),
    path('download_result_df_csv/',views.download_result_df_csv,name='consol_download'),
    path('get_columns/', views.get_columns, name='get_columns'),
    path('fetch_column_data/', views.fetch_column_data, name='fetch_column_data'),
    path('combined-results/', views.combined_results, name='combined_results'),
    path('handle_custom_selected_values/', views.handle_custom_selected_values, name='handle_custom_selected_values'),
    path('download_checks/', views.download_checks, name='download_checks'),
    path('download_excel/', views.download_excel, name='download_excel'),
    path('get_columns/', views.get_columns, name='get_columns'),
    path('process_mapping_data/', views.process_mapping_data, name='process_mapping_data'),
    path('flush_session/', views.flush_session, name='flush_session'),
    path('quarter-data/', views.quarter_data, name='quarter_data'),
]
